services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kafka
    environment:
      DATABASE_URL: postgresql://postgres:123@db/api-gateway
      DATABASE_USER: postgres
      DATABASE_PASS: 123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: api-gateway
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USER: 93b18c8f2ae5c7
      MAIL_PASS: 2a9ef42df82451
      NODE_ENV: localhost
      SECRET_KEY: api_nest
      ACCESS_TOKEN_EXPIRES_IN: 1h
      REFRESH_TOKEN_EXPIRES_IN: 2
      HOST_IP: api-gateway
      API_PORT: 3000
      KAFKA_BROKER: kafka:9092

  email-api:
    build:
      context: ./email-api
      dockerfile: Dockerfile
      target: production
    ports:
      - "3002:3002"
    depends_on:
      - db
      - kafka
    environment:
      DATABASE_URL: postgresql://postgres:123@db/email
      DATABASE_USER: postgres
      DATABASE_PASS: 123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: email
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USER: 93b18c8f2ae5c7
      MAIL_PASS: 2a9ef42df82451
      NODE_ENV: localhost
      SECRET_KEY: api_nest
      ACCESS_TOKEN_EXPIRES_IN: 1h
      REFRESH_TOKEN_EXPIRES_IN: 2
      HOST_IP: email-api
      API_PORT: 3002
      KAFKA_BROKER: kafka:9092

  customers-api:
    build:
      context: ./customers-api
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
    depends_on:
      - db
      - kafka
    environment:
      DATABASE_URL: postgresql://postgres:123@db/customer
      DATABASE_USER: postgres
      DATABASE_PASS: 123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: customer
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USER: 93b18c8f2ae5c7
      MAIL_PASS: 2a9ef42df82451
      NODE_ENV: localhost
      SECRET_KEY: api_nest
      ACCESS_TOKEN_EXPIRES_IN: 1h
      REFRESH_TOKEN_EXPIRES_IN: 2
      HOST_IP: customers-api
      API_PORT: 3001
      KAFKA_BROKER: kafka:9092
volumes:
  pgdata: {}