apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: deivisonisidoro/notification-service:latest
          command: ["sh", "-c", "pnpm exec prisma migrate deploy && node dist/presentation/fastify/server.js"]
          envFrom:
            - configMapRef:
                name: notification-service-config
          ports:
            - containerPort: 3002
              name: http