apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-service-config
data:
  DATABASE_URL: "postgresql://postgres:123@db:5432/customer-service?schema=public"
  DATABASE_USER: "postgres"
  DATABASE_PASS: "123"
  DATABASE_HOST: "db"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "customer-service"
  NODE_ENV: "production"
  HOST_IP: "customers-service"
  API_PORT: "3001"
  KAFKA_BROKER: "kafka:9092"
